### PR TITLE
HCT REDCap export

### PR DESCRIPTION
**Pull request by davereinhart**
Adds the new HCT REDCap server's API URL environment variable, and adds the new HCT 2021-2022 project on that server to the UW EHS reporting process.

### CODE REVIEW

**Comment by davereinhart** [comment]
Prior to deployment, this will need an environment variable `REDCAP_API_TOKEN_hct.redcap.rit.uw.edu_45` added on the production server, containing an API token for the new project.

**Comment by davereinhart** [comment]
[HCT: Add new Redcap project to HCT ETL](https://trello.com/c/wjqw3qoe/1151-hct-add-new-redcap-project-to-hct-etl)

**Comment by davereinhart** [comment]
[HCT: Add new Redcap project to export for EHS transfer](https://trello.com/c/D81tKV7S/1156-hct-add-new-redcap-project-to-export-for-ehs-transfer)

**Review by kschwabefry — APPROVED** [review]

**Comment by davereinhart** [comment]
Deployed.

**Pull request merged**
