### PR TITLE
Fix broken infrastructure documentation link

### PR DESCRIPTION
**Pull request by kschwabefry**

### CODE REVIEW

**Review by jccraft-uw — APPROVED** [review]

**Review by tsibley — APPROVED** [review]
Thanks! Also, ha, it's still using `zeXLc2p0`… :detective:

**Comment by kschwabefry** [comment]
> Thanks! Also, ha, it's still using `zeXLc2p0`… 🕵️

Yeah! :joy: Was that an account id before the github org was named "seattle flu"?

**Comment by kschwabefry** [comment]
Fixed zeXLc2p0 --> seattleflu

**Comment by kschwabefry** [comment]
Deployed

**Comment by tsibley** [comment]
Yep. zeXLc2p0 was the random name I choose for the SFS GitHub account before anyone had settled on what the nascent study would be called. I wanted to get started with implementation before branding was finalized.

**Pull request merged**
