### PR TITLE
upload-sch-retrospective-data-pulls: Use .xls instead of .csv

### PR DESCRIPTION
**Pull request by kairstenfay**
Amanda is not longer sending us retrospective SCH data in CSV format.
When running the automated `upload-sch-retrospective-data-pulls` script,
check for `.xls` file extensions instead of `.csv`.

-------

Depends on https://github.com/seattleflu/id3c-customizations/pull/53

### CODE REVIEW

**Comment by kairstenfay** [comment]
I thought about checking for either .csv or .xls files when doing my pairing comparison to check for matched .ndjson data. However, it seemed overly complicated, especially given the fact that Amanda will no longer be sending us CSVs.

**Comment by kairstenfay** [comment]
[Read xls or csv in `clinical parse-sch`](https://trello.com/c/3uZSm38H/344-read-xls-or-csv-in-clinical-parse-sch)

**Comment by tsibley** [comment]
> I thought about checking for either .csv or .xls files when doing my pairing comparison to check for matched .ndjson data. However, it seemed overly complicated, especially given the fact that Amanda will no longer be sending us CSVs.

I think it's fine to just switch to .xls, but supporting .csv, .xls, and .xlsx should be as small a change as:

```diff
diff --git a/bin/upload-sch-retrospective-data-pulls b/bin/upload-sch-retrospective-data-pulls
index 5da5756..9fb7bcd 100755
--- a/bin/upload-sch-retrospective-data-pulls
+++ b/bin/upload-sch-retrospective-data-pulls
@@ -5,6 +5,7 @@
 #
 
 set -euo pipefail
+shopt -s extglob
 
 # Change to the top-level of the backoffice checkout
 cd "$(dirname "$0")/.."
@@ -49,19 +50,21 @@ main() {
     # SCH data upload of 2019, the column naming scheme changed. The CLI command
     # was then changed, now causing earlier data pulls to fail on parsing.
 
-    # Also only include `.xls` file extensions. Since the 2020-02-10 dataset,
-    # Amanda has only sent us Excel workbooks.
+    # Since the 2020-02-10 dataset, Amanda has only sent us Excel workbooks,
+    # but preserve support for CSV too.
     aws s3 cp --recursive \
         s3://fh-pi-bedford-t/seattleflu/sch/ \
         "$datadir" \
         --exclude "*" \
+        --include "SFS_Year2_Main_Data_2020*.csv" \
         --include "SFS_Year2_Main_Data_2020*.xls" \
+        --include "SFS_Year2_Main_Data_2020*.xlsx" \
         --include "SFS_Year2_Main_Data_2020*.ndjson"
     echo
 
-    for retrospective_xls_file in "$datadir"/*.xls
+    for retrospective_spreadsheet_file in "$datadir"/*.@(csv|xls|xlsx)
     do
-        retrospective_ndjson_file="${retrospective_xls_file%.xls}.ndjson"
+        retrospective_ndjson_file="${retrospective_spreadsheet_file%.@(csv|xls|xlsx)}.ndjson"
 
         echo "Checking for parsed retrospective data «$retrospective_ndjson_file»"
         if [[ -e "$retrospective_ndjson_file" ]]; then
@@ -72,7 +75,7 @@ main() {
 
         echo "No parsed data found. Parsing now"
         echo
-        if ! $id3c clinical parse-sch "$retrospective_xls_file" > "$retrospective_ndjson_file"; then
+        if ! $id3c clinical parse-sch "$retrospective_spreadsheet_file" > "$retrospective_ndjson_file"; then
             echo "Something went wrong when parsing the retrospective data"
             exit 1
         fi
```

**Comment by kairstenfay** [comment]
> I think it's fine to just switch to .xls, but supporting .csv, .xls, and .xlsx should be as small a change as:

Oh that's not too complicated of a solution. Thanks! I fixed up my commit to include your changes from the diff you shared.

**Comment by tsibley** [comment]
Looks good!

**Pull request merged**
