### PR TITLE
Turn off the website-science-map cronjob

### PR DESCRIPTION
**Pull request by kairstenfay**
The SFS website has not been active for some time. Stop installing the
website-science-map cronjob, but keep the file in case we want to turn
the job back on again.

### CODE REVIEW

**Comment by tsibley** [comment]
Note that the crontab will also have to be manually removed from its installed location when deploying this change.

I would probably delete the crontab and associated export script from the repo. We can always pull them out of git history later.

**Comment by kairstenfay** [comment]
> Note that the crontab will also have to be manually removed from its installed location when deploying this change.

Noted 

> I would probably delete the crontab and associated export script from the repo. We can always pull them out of git history later.

The crontab and export script files are deleted in the latest version of the commit.

**Comment by tsibley** [comment]
Oh, would you also delete `s3://seattle-flu-study/samples.geojson` when you deploy this?

**Comment by kairstenfay** [comment]
> Oh, would you also delete `s3://seattle-flu-study/samples.geojson` when you deploy this?

The asociated crontab file on the backoffice server and s3 geojson file have both been deleted.

**Pull request merged**
